### ISSUE TITLE
使用train.py从零开始训练出现UnboundLocalError: local variable 'summary_val' referenced before assignment

### ISSUE THREAD

**Issue by imliusu** [LeslieZhoa/tensorflow-facenet#10]
在使用 train.py 从头开始训练时，出现
Step: 1/9, accuracy: 0.155556, center loss: 0.998996, cross loss: 2.833399, Total Loss: 9.798814 ,lr:0.010000
Traceback (most recent call last):
  File "train.py", line 283, in <module>
    main()
  File "train.py", line 201, in main
    val_writer.add_summary(summary_val, global_step=epoch)
UnboundLocalError: local variable 'summary_val' referenced before assignment

尝试加入 global summary_val 依然报错

**Comment by LeslieZhoa** [comment]
https://github.com/LeslieZhoa/tensorflow-facenet/blob/f875d0d4c244ac596b355cb4dbc0ab8fa1ed0edb/train/train.py#L188
如果你没有修改这里，应该不会有错，希望对你有所帮助

**Comment by yimuart** [comment]
你好，我也遇到了同样的问题，尝试无果，请问你解决这个问题了吗？我想请问如何解决的?谢谢！

> 在使用 train.py 从头开始训练时，出现 Step: 1/9, accuracy: 0.155556, center loss: 0.998996, cross loss: 2.833399, Total Loss: 9.798814 ,lr:0.010000 Traceback (most recent call last): File "train.py", line 283, in main() File "train.py", line 201, in main val_writer.add_summary(summary_val, global_step=epoch) UnboundLocalError: local variable 'summary_val' referenced before assignment
> 
> 尝试加入 global summary_val 依然报错

**Comment by imliusu** [comment]
> 你好，我也遇到了同样的问题，尝试无果，请问你解决这个问题了吗？我想问如何解决这个问题？谢谢！
> 
> > 在使用 train.py 从头开始​​训练时，出现 Step: 1/9, accuracy: 0.155556, center loss: 0.998996, cross loss: 2.833399, Total Loss: 9.798814 ,lr:0.010000 Traceback (most recent call last): File "train .py”，第 283 行，在 main() 文件“train.py”，第 201 行，在 main val_writer.add_summary(summary_val, global_step=epoch) UnboundLocalError：在赋值之前引用了局部变量 'summary_val'
> > 尝试加入 global summary_val 仍然报错
你好，可以检查数据集数量是否符合一定比例？忘记是偶数还是三倍了。
我有点忘了是数据集数量不足还是这个倍数问题，可以都尝试一下看看能不能解决。

**Comment by imliusu** [comment]
> 你好，我也遇到了同样的问题，尝试无果，请问你解决这个问题了吗？我想如何解决这个问题？谢谢！
> 
> > 在使用 train.py 从头开始​​训练时，出现 Step: 1/9, accuracy: 0.155556, center loss: 0.998996, cross loss: 2.833399, Total Loss: 9.798814 ,lr:0.010000 Traceback (最近一次调用最后一次): File "train .py"，第 283 行，第 201 行，"train.py"，第 201 行，在 main val_writer 主行。
> > 尝试加入 global summary_val 仍然报错


你好，可以检查数据集数量是否符合一定比例？忘记是偶数还是三倍了。
我有点忘了是数据集数量不足还是这个倍数问题，可以都尝试一下看看能不能解决。

**Comment by imliusu** [comment]
你好，可以检查数据集数量是否符合一定比例？忘记是偶数还是三倍了。
我有点忘了是数据集数量不足还是这个倍数问题，可以都尝试一下看看能不能解决。


> 你好，我也遇到了同样的问题，尝试无果，请问你解决这个问题了吗？我想请问如何解决的?谢谢！
> 
> > 在使用 train.py 从头开始训练时，出现 Step: 1/9, accuracy: 0.155556, center loss: 0.998996, cross loss: 2.833399, Total Loss: 9.798814 ,lr:0.010000 Traceback (most recent call last): File "train.py", line 283, in main() File "train.py", line 201, in main val_writer.add_summary(summary_val, global_step=epoch) UnboundLocalError: local variable 'summary_val' referenced before assignment
> > 尝试加入 global summary_val 依然报错
